### ISSUE TITLE
arguments as a parameter name is not allowed in strict mode.

### ISSUE THREAD

**Issue by base698** [ciaranj/node-oauth#178]
https://github.com/ciaranj/node-oauth/blob/master/lib/oauth.js#L169

arguments as a parameter name is not allowed in strict mode.

SyntaxError: Parameter name eval or arguments is not allowed in strict mode
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/justinthomas/workspaces/soundselect/node_modules/passport-soundcloud/node_modules/passport-oauth/node_modules/oauth/index.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by abhinavrastogi** [comment]
Why no action on this yet? Valid issue and acceptable solution.
